export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
  NOT_FOUND_ERROR: "NOT_FOUND_ERROR",
  CONFLICT_ERROR: "CONFLICT_ERROR",
  INFRASTRUCTURE_ERROR: "INFRASTRUCTURE_ERROR",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR"
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
